car_sales/car_sales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import HomeView, ContactUsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
    path('user/', include('user.urls', namespace='user')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

car_sales/user/urls.py
from django.urls import path
from user.views import LoginView, LogoutView, DashboardView, RegisterView

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('register/', RegisterView.as_view(), name='register'),
]

car_sales/user/models.py
from django.db import models
from django.contrib.auth.models import User

class ContactUs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=127, blank=True)
    email = models.EmailField(blank=True, null=True)
    car_image = models.ImageField(null=True)
    query = models.TextField(max_length=511)

car_sales/user/forms.py
from django.forms import ModelForm
from user.models import ContactUs

class ContactUsForm(ModelForm):

    class Meta:
        model = ContactUs
        exclude = ('user',)

class ContactUsAuthenticatedForm(ModelForm):

    class Meta:
        model = ContactUs
        fields = ('car_image','query',)

car_sales/user/views.py
from email import message
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views import View
from django.contrib import messages

from user.models import ContactUs
from user.forms import ContactUsForm, ContactUsAuthenticatedForm

class LoginView(View):

    form = AuthenticationForm()

    def get(self, request):
        return render(request, 'user/login.html', context={'form':self.form})

    def post(self, request):
        if 'username' not in request.POST.keys():
            messages.error(request, 'Missing username')
            return redirect('login')
        if 'password' not in request.POST.keys():
            messages.error(request, 'Missing password')
            return redirect('login')

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, 'Logged in Successfully')
            return redirect('user:dashboard')
        else:
            messages.error(request, 'Invalid credentials')
            return render(request, 'login.html', context={'form':self.form()})

class LogoutView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            messages.error(request, 'User already logged out')
        else:
            logout(request)
            messages.success(request, 'Logged out successfully')
        return redirect('home')

class RegisterView(View):

    def get(self, request):
        form = UserCreationForm()
        return render(request, 'user/register.html', context={'form':form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registered successfully')
            return redirect('user:dashboard')
        else:
            messages.error(request, 'Invalid data')
            return render(request, 'user/register.html', context={'form':form})

class ContactUsView(View):

    def get(self, request):
        form = ContactUsForm()
        return render(request, 'user/contact_us.html', context={'form':form})

    def post(self, request):
        data = request.POST.dict()
        user_auth = request.user.is_authenticated
        if user_auth:
            data.update(
                {
                    'email':request.user.email if request.user.email else ''
                }
            )
        form = ContactUsForm(data, request.FILES)
        if form.is_valid():
            query = form.save()
            if user_auth:
                query.user = request.user
                query.save()
            messages.success(request, 'Successfully saved query')
            if user_auth:
                return redirect('user:dashboard')
            else:
                return redirect('contact-us')
        else:
            print(form.errors)
            messages.error(request, 'Invalid data')
            if user_auth:
                return redirect('user:dashboard')
            else:
                return render(request, 'user/contact_us.html', context={'form':form})

class HomeView(View):

    def get(self, request):
        return render(request, 'user/home.html')

class DashboardView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            messages.warning(request, 'Please login')
            return redirect('user:login')
        queries = ContactUs.objects.filter(user=request.user)
        form = ContactUsAuthenticatedForm()
        return render(request, 'user/dashboard.html', context={'form':form, 'queries': queries})

car_sales/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <style>
      html {
        height: 100%;
        width: 100%;
      }
      body {
        background-image: url('https://media.istockphoto.com/photos/new-cars-in-showroom-blurred-defocused-background-picture-id1176032554?k=20&m=1176032554&s=612x612&w=0&h=vgdLNexbTthDrURGMPtTZE6axtCFFy1yhE4IOm5TcRI=');
        background-repeat: no-repeat;
        background-size: 100% 100%;
        height: 100%;
        width: 100%;
      }
    </style>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                  {{ message }}
                </div>
              </div>
        {% endfor %}
    {% endif %}
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Car Sales</a>
        {% if user.is_authenticated %}
          <a href="{% url 'user:logout' %}" class="d-flex">
            <button class="btn btn-primary">Logout</button class="btn btn-primary">
          </a>
        {% endif %}
      </div>
    </nav>
    <br>
    <div class="container" style="background-color: rgba(230, 226, 228, 0.8);">
      <br>
      <div class="row justify-content-center">
        <div class="col-8">
          {% block content %}
          <h1>Hi!</h1>
          {% endblock content %}
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

car_sales/user/templates/user/contact_us.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'contact-us' %}" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p|crispy }}
    <button class="btn btn-primary" type="submit">Submit Query</button class="btn btn-primary">
</form>
{% endblock content %}

car_sales/user/templates/user/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'contact-us' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Submit Query</button class="btn btn-primary">
</form>
<ul>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Query ID</th>
                <th scope="col">Image</th>
                <th scope="col">Query</th>
            </tr>
        </thead>
        <tbody>
            {% for query in queries %}
                <tr>
                    <td>{{ query.id }}</td>
                    <td>
                        <img src="{{ query.car_image.url }}" alt="{{ query.id }}">
                    </td>
                    <td>{{ query.query }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</ul>
{% endblock content %}

car_sales/user/templates/user/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<div style="text-align: center;">
    <h1>Home</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'user:dashboard' %}">
            <button class="btn btn-primary">Dashboard</button class="btn btn-primary">
        </a>
    {% else %}
        <a href="{% url 'user:login' %}">
            <button class="btn btn-primary">Login</button class="btn btn-primary">
        </a>
        <a href="{% url 'user:register' %}">
            <button class="btn btn-primary">Register</button class="btn btn-primary">
        </a>
    {% endif %}
</div>
{% endblock content %}

car_sales/user/templates/user/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button class="btn btn-primary">
</form>
{% endblock content %}

car_sales/user/templates/user/register.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Register</button class="btn btn-primary">
</form>
{% endblock content %}